# Generated by Django 3.2.7 on 2021-09-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210911_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='thesis',
            field=models.FileField(default='', upload_to='uploads'),
        ),
    ]
