# Generated by Django 3.2.7 on 2021-09-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_student_thesis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='thesis',
            field=models.FileField(null=True, upload_to='uploads'),
        ),
    ]
