# Generated by Django 3.2.7 on 2021-09-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20210912_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
