# Generated by Django 3.2.7 on 2021-09-12 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_alter_messagemodel_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('students', models.ManyToManyField(related_name='class_notice', to='webapp.Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='webapp.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
