# Generated by Django 3.2.7 on 2021-09-12 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_classnotice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassNotice',
            new_name='GroupNotice',
        ),
    ]
