# Generated by Django 3.2.7 on 2021-09-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_rename_classnotice_groupnotice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupnotice',
            name='students',
            field=models.ManyToManyField(related_name='group_notice', to='webapp.Student'),
        ),
    ]
