# Generated by Django 3.2.7 on 2021-09-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_alter_groupnotice_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='thesis',
            field=models.CharField(default='', max_length=250),
        ),
    ]
