# Generated by Django 3.2.7 on 2021-10-01 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadmodel',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='webapp.profiluser'),
        ),
        migrations.AlterField(
            model_name='threadmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='webapp.profiluser'),
        ),
    ]
